# Generated by Django 2.1.2 on 2018-10-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='group',
            new_name='rating_table',
        ),
    ]
